<?php

$settings["title"] ='Infinity CMS';
$settings["phone"] ='0555 123 45 67';
$settings["fax"] ='0555 123 45 67';
$settings["email"] ='info@afsakar.com';
$settings["address"] ='Ankara/Türkiye';
$settings["footer_text"] ='<p style="">Copryrigt ©&nbsp; <a href="http://www.afsakar.com" target="_blank" style=""><b style=""><font color="#ffffff">Infinity CMS</font></b></a> |&nbsp;Tüm hakkı saklıdır.</p>';
$settings["meta_title"] ='Azad Furkan ŞAKAR CMS';
$settings["meta_description"] ='Azad Furkan ŞAKAR CMS';
$settings["meta_keywords"] ='azad,furkan,cms';
$settings["about_us_title"] ='Hakkımızda';
$settings["about_us"] ='<p style="text-align: justify; ">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>Mauris blandit augue eu sagittis maximus</b>. Donec vitae cursus ex. Quisque fringilla nibh ut dolor interdum varius. Maecenas elit enim, imperdiet quis luctus sit amet, cursus eget sem. In ultrices convallis sem, quis placerat purus posuere quis. Proin bibendum purus ut vestibulum iaculis. Praesent sit amet tempus dolor. Morbi bibendum mattis lacus, et pellentesque est congue nec. Vivamus sapien erat, molestie eget nulla quis, fringilla commodo eros. Aliquam posuere mi a metus auctor, sed imperdiet mauris rhoncus. Praesent vel placerat eros.</p>';
$settings["mission"] ='<p><span style="color: rgb(119, 119, 119); font-family: Roboto, sans-serif; font-size: 16px;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod saepe ad asperiores a unde illum adipisci minus magni. Modi totam deleniti doloribus iure! Amet aliquam totam dolorem excepturi optio magnam!</span><br></p>';
$settings["vision"] ='<p><span style="color: rgb(119, 119, 119); font-family: Roboto, sans-serif; font-size: 16px;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod saepe ad asperiores a unde illum adipisci minus magni. Modi totam deleniti doloribus iure! Amet aliquam totam dolorem excepturi optio magnam!</span><br></p>';
$settings["map_code"] ='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12238.920726755347!2d32.8369439!3d39.925054!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd3862ea8248d08a0!2sAn%C4%B1tkabir!5e0!3m2!1str!2str!4v1604608784595!5m2!1str!2str';
$settings["googlemap_isopen"] ='0';
$settings["analytics_code"] ='UA-117495992-1';
$settings["facebook"] ='http://www.facebook.com';
$settings["twitter"] ='http://www.twitter.com';
$settings["instagram"] ='http://www.instagram.com';
$settings["linkedin"] ='http://www.linkedin.com';
$settings["color"] ='danger';
$settings["contact_text"] ='<p style="">There are many variations of passages of Lorem Ipsum available, but the majority Lorem Ipsum available.</p>';
$settings["contact_template"] ='<table border="0" cellpadding="0" cellspacing="0" width="100%" style="text-size-adjust: 100%; font-family: " times="" new="" roman";="" font-size:="" medium;"=""><tbody><tr><td align="center" bgcolor="#e9ecef" style="text-size-adjust: 100%;"><p><br></p><p><img src="myLogo" width="200"></p></td></tr><tr><td align="center" bgcolor="#e9ecef" style="text-size-adjust: 100%;"><br></td></tr><tr><td align="center" bgcolor="#e9ecef" style="text-size-adjust: 100%;"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="text-size-adjust: 100%; max-width: 600px;"><tbody><tr><td align="left" bgcolor="#ffffff" style="padding: 24px; text-size-adjust: 100%; font-family: " source="" sans="" pro",="" helvetica,="" arial,="" sans-serif;="" font-size:="" 16px;="" line-height:="" 24px;="" border-radius:="" 0px="" 2px="" 2px;"=""><p><font face="Verdana"><b>Kimden</b>: myName (myMail)</font></p><p><font face="Verdana"><b>Telefon</b>: myPhone</font></p><p><font face="Verdana"><b>Mesaj</b>:</font></p><p><font face="Verdana">myMessage</font></p></td></tr><tr><td align="left" bgcolor="#ffffff" style="padding: 24px; text-size-adjust: 100%; font-family: " source="" sans="" pro",="" helvetica,="" arial,="" sans-serif;="" font-size:="" 16px;="" line-height:="" 24px;="" border-bottom:="" 3px="" solid="" rgb(212,="" 218,="" 223);"=""><p><br></p></td></tr></tbody></table></td></tr><tr><td align="center" bgcolor="#e9ecef" style="padding: 24px; text-size-adjust: 100%;"><br></td></tr></tbody></table>';
$settings["reply_template"] ='<table border="0" cellpadding="0" cellspacing="0" width="100%" times="" new="" roman";="" font-size:="" medium;"="" style="text-size-adjust: 100%;"><tbody><tr><td align="center" bgcolor="#e9ecef" style="text-size-adjust: 100%;"><p><br></p><p><img src="myLogo" width="200"></p></td></tr><tr><td align="center" bgcolor="#e9ecef" style="text-size-adjust: 100%;"><br></td></tr><tr><td align="center" bgcolor="#e9ecef" style="text-size-adjust: 100%;"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="text-size-adjust: 100%; max-width: 600px;"><tbody><tr><td align="left" bgcolor="#ffffff" source="" sans="" pro",="" helvetica,="" arial,="" sans-serif;="" font-size:="" 16px;="" line-height:="" 24px;="" border-radius:="" 0px="" 2px="" 2px;"="" style="padding: 24px; text-size-adjust: 100%;"><p style="text-align: center; "><font face="Verdana">myTitle</font></p><p style="text-align: center; "><font face="Verdana"><br></font></p><p><b style="font-family: Verdana; background-color: transparent;">Mesaj</b><span style="font-family: Verdana; background-color: transparent;">:</span><br></p><p><font face="Verdana">myMessage</font></p><p><font face="Verdana"><br></font></p><p><font face="Verdana">oldMessage</font></p></td></tr><tr><td align="left" bgcolor="#ffffff" source="" sans="" pro",="" helvetica,="" arial,="" sans-serif;="" font-size:="" 16px;="" line-height:="" 24px;="" border-bottom:="" 3px="" solid="" rgb(212,="" 218,="" 223);"="" style="padding: 24px; text-size-adjust: 100%;"><p><br></p></td></tr></tbody></table></td></tr><tr><td align="center" bgcolor="#e9ecef" style="padding: 24px; text-size-adjust: 100%;"><br></td></tr></tbody></table>';
